export interface Option {
  value: number | string;
  label: string;
}

export const ministries: Option[] = [
  { value: 1, label: "All Ministries" },
  { value: 2, label: "Ministry of Consumer Affairs Food and Public Distribution System" },
  { value: 3, label: "Ministry of Culture" },
  { value: 4, label: "Ministry of Defence" },
  { value: 5, label: "Ministry of Development of North Eastern Region" },
  { value: 6, label: "Ministry of Earth Sciences" },
  { value: 7, label: "Ministry of Education" },
  { value: 8, label: "Ministry of Electronics and Information Technology" },
  { value: 9, label: "Ministry of Environment Forest and Climate Change" },
  { value: 10, label: "Ministry of Finance" },
  { value: 11, label: "Ministry of Food Processing Industries" },
  { value: 12, label: "Ministry of Health and Family Welfare" },
  { value: 13, label: "Ministry of Heavy Industries" },
  { value: 14, label: "Ministry of Home Affairs" },
  { value: 15, label: "Ministry of Housing and Urban Affairs" },
  { value: 16, label: "Ministry of Information and Broadcasting" },
  { value: 17, label: "Ministry of Jal Shakti" },
  { value: 18, label: "Ministry of Labour and Employment" },
  { value: 19, label: "Ministry of Law and Justice" },
  { value: 20, label: "Ministry of Micro Small and Medium Enterprises" },
  { value: 21, label: "Ministry of Mines" },
  { value: 22, label: "Ministry of Minority Affairs" },
  { value: 23, label: "Ministry of New and Renewable Energy" },
  { value: 24, label: "Ministry of Panchayati Raj" },
  { value: 25, label: "Ministry of Parliamentary Affairs" },
  { value: 26, label: "Ministry of Personnel Public Grievances and Pensions" },
  { value: 27, label: "Ministry of Petroleum and Natural Gas" },
  { value: 28, label: "Ministry of Ports Shipping and Waterways" },
  { value: 29, label: "Ministry of Power" },
  { value: 30, label: "Ministry of Railways" },
  { value: 31, label: "Ministry of Road Transport and Highways" },
  { value: 32, label: "Ministry of Rural Development" },
  { value: 33, label: "Ministry of Science and Technology" },
  { value: 34, label: "Ministry of Skill Development and Entrepreneurship" },
  { value: 35, label: "Ministry of Social Justice and Empowerment" },
  { value: 36, label: "Ministry of Statistics and Programme Implementation" },
  { value: 37, label: "Ministry of Steel" },
  { value: 38, label: "Ministry of Textiles" },
  { value: 39, label: "Ministry of Tourism" },
  { value: 40, label: "Ministry of Tribal Affairs" },
  { value: 41, label: "Ministry of Women and Child Development" },
  { value: 42, label: "Ministry of Youth Affairs and Sports" },
  { value: 43, label: "Ministry of External Affairs" },
  { value: 44, label: "Prime Minister's Office" },
  { value: 45, label: "Ministry of Agriculture and Farmers' Welfare" },
  { value: 46, label: "Ministry of Animal Husbandry Dairying and Fisheries" },
  { value: 47, label: "Ministry of Chemicals and Fertilizers" },
  { value: 48, label: "Ministry Of Preschools" },
  { value: 49, label: "Ministry of Coal" },
  { value: 50, label: "Ministry of Commerce and Industry" },
  { value: 51, label: "Ministry of Ayush" },
  { value: 52, label: "Ministry of Corporate Affairs" },
  { value: 53, label: "Niti Aayog Yojana" },
  { value: 54, label: "Health Department" },
  { value: 55, label: "Examination Ministry" },
  { value: 56, label: "Ministry of Communications" },
  { value: 57, label: "Forest Ministry of India" },
  { value: 58, label: "Ministry of Forest" }
];
